language: node_js
node_js:
  - "10.16.3"

sudo: true
dist: bionic

addons:
  apt:
    packages:
      - firefox

install:
  - npm install

script:
  - ls
  - echo "{\"headless\": true}" > test/config.json
  - npm test
